### ISSUE TITLE
Array of unique elements

### ISSUE THREAD

**Issue by mistadikay** [leebyron/testcheck-js#13]
Is there any way to generate an array of _unique_ elements? Couldn't find anything in docs.

**Comment by davidmccabe** [comment]
If you have a `uuid` function lying around, you can do this:

```
const genUUID = gen.map(uuid, gen.null)
```

If you want unique integers and no dependencies, you could do something like:

```
const alternatingSign = i => (i % 2) * 2 - 1;
const makeUniqueIntGen = () => {
  let n = 0;
  return gen.map(
    i => {
      n += i;
      return n * alternatingSign(n);
    },
    gen.strictPosInt
  );
};
```

This generates positive and negative numbers so that the generated numbers are not ordered, which might be an unwanted invariant (though the magnitudes are still ordered).

**Comment by leebyron** [comment]
Just a forewarning that `gen.map(uuid, gen.null)` is a red flag - anything that maps over null should produce the same value every time. If the `genUUID` function uses any randomness then it is not a pure function of its input and test shrinking will fail.

`gen.map` is still probably what you want to use though. You could `gen.map` over a `gen.int` to use as the length of the array you want to produce, and then produce arrays of consecutive integers `[0, 1, 2, 3]` to guarantee randomness.

There are just so many different things that "an array of unique elements" could potentially produce that it may need to write your own generator using `map` to produce something meaningful to your test.
